project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
    toc: true

  # docx: default
  # jats: default
  pdf: default

number-sections: true
bibliography: references.bib
